"""PostgreSQL persistence layer (asyncpg): schema, pooled connections, transactions, batched retention purge.

Conventions for every caller:
- Statements are written with `?` placeholders; `translate()` turns them into `$n` in order, so dynamic builders stay
  order-safe. A `?` never appears inside a SQL literal here, and the jsonb `?` operators are refused on purpose.
- Every `str` parameter has NUL bytes replaced (`clean()`): PostgreSQL text refuses them, SQLite accepted them.
- Inserts that need the new id say `RETURNING id` and go through `fetchval()`; `execute()` returns rows affected.
- Inside `transaction()` use only the `tx.*` methods: `db.*` runs on another pooled connection.
- `execute()` with no parameters runs the simple-query protocol, which accepts several statements; it therefore
  refuses a `;` (the schema runner in `connect()` is the only multi-statement path).
"""

from __future__ import annotations

import asyncio
import functools
import json
import logging
import os
import re
import time
from contextlib import asynccontextmanager
from typing import Any, AsyncIterator, Iterable
from urllib.parse import urlsplit, urlunsplit

import asyncpg

log = logging.getLogger("mtr-tracker.db")

IntegrityError = asyncpg.IntegrityConstraintViolationError
Row = asyncpg.Record

SCHEMA_VERSION = 4

# Matches the credentials of the bundled docker-compose service; a server elsewhere is named in MTR_TRACKER_DATABASE_URL.
DEFAULT_DATABASE_URL = "postgresql://mtr:mtr@127.0.0.1:5432/mtr_tracker"
# How long a statement waits for a pooled connection before failing loudly; a saturated pool must never hang silently.
ACQUIRE_TIMEOUT = 30.0
# Rows per executemany round trip: asyncpg cannot be cancelled cleanly while it is still transmitting a batch, so a
# chunk stays well below its write buffers (about 128 KiB).
EXECUTEMANY_CHUNK = 200
# Tables with an identity column, in foreign-key order (the migration copies and re-sequences them in this order).
ID_TABLES = ("targets", "runs", "hops", "events")

TABLES = """
CREATE TABLE IF NOT EXISTS meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    host TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'mtr',
    options TEXT NOT NULL DEFAULT '{}',
    description TEXT NOT NULL DEFAULT '',
    tags TEXT NOT NULL DEFAULT '[]',
    interval_sec INTEGER NOT NULL DEFAULT 300,
    count INTEGER NOT NULL DEFAULT 10,
    probe_interval DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    protocol TEXT NOT NULL DEFAULT 'icmp',
    port INTEGER,
    packet_size INTEGER NOT NULL DEFAULT 64,
    ip_version TEXT NOT NULL DEFAULT 'auto',
    max_hops INTEGER NOT NULL DEFAULT 30,
    enabled INTEGER NOT NULL DEFAULT 1,
    notify INTEGER NOT NULL DEFAULT 1,
    alert_loss_pct DOUBLE PRECISION NOT NULL DEFAULT 5.0,
    alert_latency_ms DOUBLE PRECISION NOT NULL DEFAULT 200.0,
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    next_run_at DOUBLE PRECISION,
    last_status TEXT NOT NULL DEFAULT 'pending'
);

CREATE TABLE IF NOT EXISTS runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_id BIGINT NOT NULL REFERENCES targets(id) ON DELETE CASCADE,
    started_at DOUBLE PRECISION NOT NULL,
    finished_at DOUBLE PRECISION,
    duration_ms DOUBLE PRECISION,
    status TEXT NOT NULL,
    error TEXT,
    src TEXT,
    dst_ip TEXT,
    reached INTEGER NOT NULL DEFAULT 0,
    hop_count INTEGER NOT NULL DEFAULT 0,
    sent INTEGER,
    loss_pct DOUBLE PRECISION,
    last_ms DOUBLE PRECISION,
    avg_ms DOUBLE PRECISION,
    best_ms DOUBLE PRECISION,
    worst_ms DOUBLE PRECISION,
    stdev_ms DOUBLE PRECISION,
    jitter_avg_ms DOUBLE PRECISION,
    jitter_max_ms DOUBLE PRECISION,
    route_hash TEXT,
    route_changed INTEGER NOT NULL DEFAULT 0,
    command TEXT,
    details TEXT
);

CREATE TABLE IF NOT EXISTS hops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
    hop_no INTEGER NOT NULL,
    ip TEXT,
    hostname TEXT,
    asn TEXT,
    loss_pct DOUBLE PRECISION NOT NULL DEFAULT 0,
    sent INTEGER NOT NULL DEFAULT 0,
    received INTEGER NOT NULL DEFAULT 0,
    last_ms DOUBLE PRECISION,
    avg_ms DOUBLE PRECISION,
    best_ms DOUBLE PRECISION,
    worst_ms DOUBLE PRECISION,
    stdev_ms DOUBLE PRECISION,
    gmean_ms DOUBLE PRECISION,
    jitter_ms DOUBLE PRECISION,
    jitter_avg_ms DOUBLE PRECISION,
    jitter_max_ms DOUBLE PRECISION,
    jitter_int_ms DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_id BIGINT REFERENCES targets(id) ON DELETE CASCADE,
    run_id BIGINT REFERENCES runs(id) ON DELETE SET NULL,
    kind TEXT NOT NULL,
    severity TEXT NOT NULL DEFAULT 'info',
    message TEXT NOT NULL,
    details TEXT,
    created_at DOUBLE PRECISION NOT NULL
);
"""

# The secondary indexes by name: the migration drops them before its bulk copy and recreates them afterwards.
INDEXES: dict[str, str] = {
    "idx_runs_target_started": "CREATE INDEX IF NOT EXISTS idx_runs_target_started ON runs(target_id, started_at DESC)",
    "idx_runs_started": "CREATE INDEX IF NOT EXISTS idx_runs_started ON runs(started_at)",
    "idx_hops_run": "CREATE INDEX IF NOT EXISTS idx_hops_run ON hops(run_id, hop_no)",
    "idx_events_created": "CREATE INDEX IF NOT EXISTS idx_events_created ON events(created_at DESC)",
    "idx_events_target": "CREATE INDEX IF NOT EXISTS idx_events_target ON events(target_id, created_at DESC)",
    # Without this, every run deleted by the retention purge scans the whole events table for ON DELETE SET NULL.
    "idx_events_run": "CREATE INDEX IF NOT EXISTS idx_events_run ON events(run_id)",
}

SCHEMA = TABLES + "\n" + ";\n".join(INDEXES.values()) + ";\n"

DEFAULT_SETTINGS: dict[str, Any] = {
    "retention_days": 30,
    # Latency chart only: a run's route-change marker is dropped when its route appeared among this many recent
    # runs that reached the destination (load balancing); 1 shows every stored change. Events are unaffected.
    "route_memory_runs": 20,
    "asn_lookup": True,
    "reverse_dns": True,
    "webhook_url": "",
    "webhook_events": ["down", "recovered", "degraded", "route_change"],
    "pushover_enabled": False,
    "pushover_user_key": "",
    "pushover_api_token": "",
    "pushover_device": "",
    "pushover_sound": "",
    "pushover_priority": "auto",
    "pushover_events": ["down", "recovered", "degraded"],
    "base_url": "",
    "site_name": "MTR Tracker",
    # tag -> "#rrggbb"; tags without an entry get an automatic colour in the UI.
    "tag_colors": {},
    # Optional Globalping API token (globalping.io); raises the rate limits for the globalping probe type.
    "globalping_token": "",
    # MaxMind GeoLite2 credentials: the licence key enables the map on target pages (the database is
    # downloaded with it); the account ID is optional and switches to MaxMind's basic-auth download endpoint.
    "maxmind_account_id": "",
    "maxmind_license_key": "",
    # ip-api.com as the first GeoIP provider (batched lookups, no key); the MaxMind databases answer what it cannot.
    "ip_api_enabled": False,
}

# Literals, quoted identifiers and comments are skipped; a lone '?' becomes a placeholder; '?|', '?&' and '??' are refused.
_TOKEN_RE = re.compile(r"""('(?:[^']|'')*')|("(?:[^"]|"")*")|(--[^\n]*)|(/\*.*?\*/)|(\?[|&?]?)""", re.S)

# Connection failures worth waiting for (the server is starting, or not there yet) versus configuration mistakes.
_RETRY_ERRORS: tuple[type[BaseException], ...] = (
    OSError,
    asyncio.TimeoutError,
    asyncpg.CannotConnectNowError,
    asyncpg.TooManyConnectionsError,
    asyncpg.PostgresConnectionError,
)
_FATAL_ERRORS: tuple[type[BaseException], ...] = (
    asyncpg.InvalidPasswordError,
    asyncpg.InvalidAuthorizationSpecificationError,
    asyncpg.InvalidCatalogNameError,
)


@functools.lru_cache(maxsize=1024)
def translate(sql: str) -> str:
    """Rewrite `?` placeholders as `$1..$n`, left to right, outside literals, quoted identifiers and comments."""
    n = 0

    def repl(m: re.Match[str]) -> str:
        nonlocal n
        token = m.group(5)
        if token is None:
            return m.group(0)
        if token != "?":
            raise ValueError(f"operator {token!r} is not supported in SQL statements; only '?' placeholders are translated")
        n += 1
        return f"${n}"

    return _TOKEN_RE.sub(repl, sql)


def clean(params: Iterable[Any]) -> tuple[Any, ...]:
    """Parameters as asyncpg gets them: NUL bytes in text are replaced, PostgreSQL text cannot store them."""
    out: list[Any] = []
    for value in params:
        if isinstance(value, str) and "\x00" in value:
            value = value.replace("\x00", "�")
        out.append(value)
    return tuple(out)


def _affected(status: str) -> int:
    """Rows affected from a command tag: 'DELETE 5' -> 5, 'INSERT 0 3' -> 3, 'CREATE TABLE' -> 0."""
    parts = status.split()
    if parts and parts[-1].isdigit():
        return int(parts[-1])
    return 0


class _Executor:
    """The statement API shared by the pool-backed `Database` and a `Transaction` bound to one connection."""

    @asynccontextmanager
    async def _connection(self) -> AsyncIterator[asyncpg.Connection]:
        raise NotImplementedError
        yield  # pragma: no cover

    async def fetchone(self, sql: str, params: Iterable[Any] = ()) -> Row | None:
        async with self._connection() as conn:
            return await conn.fetchrow(translate(sql), *clean(params))

    async def fetchall(self, sql: str, params: Iterable[Any] = ()) -> list[Row]:
        async with self._connection() as conn:
            return list(await conn.fetch(translate(sql), *clean(params)))

    async def fetchval(self, sql: str, params: Iterable[Any] = ()) -> Any:
        """The first column of the first row; the way to get the id of an `INSERT ... RETURNING id`."""
        async with self._connection() as conn:
            return await conn.fetchval(translate(sql), *clean(params))

    async def execute(self, sql: str, params: Iterable[Any] = ()) -> int:
        """Run one statement and return the number of rows it affected."""
        args = clean(params)
        if not args and ";" in sql:
            raise ValueError("execute() runs one statement; only the schema runner may send several")
        async with self._connection() as conn:
            return _affected(await conn.execute(translate(sql), *args))

    async def executemany(self, sql: str, rows: Iterable[Iterable[Any]]) -> None:
        """Run one statement for every row, atomically.

        The rows go to the server in chunks (a task cancelled while asyncpg is still transmitting a very large batch
        would never finish cancelling) inside one transaction, unless the caller already holds one.
        """
        batch = [clean(r) for r in rows]
        if not batch:
            return
        statement = translate(sql)
        async with self._connection() as conn:
            if conn.is_in_transaction():
                for i in range(0, len(batch), EXECUTEMANY_CHUNK):
                    await conn.executemany(statement, batch[i : i + EXECUTEMANY_CHUNK])
            else:
                async with conn.transaction():
                    for i in range(0, len(batch), EXECUTEMANY_CHUNK):
                        await conn.executemany(statement, batch[i : i + EXECUTEMANY_CHUNK])


class Transaction(_Executor):
    """Statements issued inside one `Database.transaction()` block: one connection, one commit (or one rollback)."""

    def __init__(self, conn: asyncpg.Connection):
        self._conn = conn

    @property
    def connection(self) -> asyncpg.Connection:
        """The underlying connection, for asyncpg features the wrapper does not expose (COPY, savepoints)."""
        return self._conn

    @asynccontextmanager
    async def _connection(self) -> AsyncIterator[asyncpg.Connection]:
        yield self._conn


class Database(_Executor):
    """A pool of asyncpg connections plus the schema management and the maintenance helpers."""

    def __init__(self, dsn: str, *, pool_size: int = 10, connect_timeout: float = 120.0):
        self.dsn = dsn
        self.pool_size = max(2, int(pool_size))
        self.connect_timeout = float(connect_timeout)
        self._pool: asyncpg.Pool | None = None

    @property
    def pool(self) -> asyncpg.Pool:
        if self._pool is None:
            raise RuntimeError("database is not connected")
        return self._pool

    def describe(self) -> str:
        """The connection URL without its password (and without the query, which may carry one too)."""
        parts = urlsplit(self.dsn)
        netloc = re.sub(r"^([^@]*?):[^@]*@", r"\1@", parts.netloc)
        return urlunsplit((parts.scheme, netloc, parts.path, "", ""))

    @asynccontextmanager
    async def _connection(self) -> AsyncIterator[asyncpg.Connection]:
        pool = self.pool
        try:
            conn = await pool.acquire(timeout=ACQUIRE_TIMEOUT)
        except asyncio.TimeoutError:
            log.error("no database connection became free within %.0f s (pool size %d, MTR_TRACKER_DB_POOL_SIZE)", ACQUIRE_TIMEOUT, self.pool_size)
            raise RuntimeError(f"database connection pool exhausted (MTR_TRACKER_DB_POOL_SIZE={self.pool_size})") from None
        try:
            yield conn
        finally:
            # On the pool bound above: close() may have detached it from the Database meanwhile.
            await pool.release(conn)

    async def connect(self) -> None:
        """Open the pool (waiting for a server that is still starting), create the schema, stamp the version."""
        deadline = time.monotonic() + self.connect_timeout
        delay = 1.0
        attempt = 0
        while self._pool is None:
            attempt += 1
            try:
                self._pool = await asyncpg.create_pool(
                    self.dsn,
                    min_size=1,
                    max_size=self.pool_size,
                    # Bound each attempt too: a host that drops packets would otherwise wait asyncpg's 60 s per try.
                    timeout=max(1.0, min(60.0, deadline - time.monotonic())),
                    server_settings={"application_name": "mtr-tracker"},
                )
            except _FATAL_ERRORS as exc:
                raise RuntimeError(f"cannot connect to PostgreSQL at {self.describe()}: {exc} (check MTR_TRACKER_DATABASE_URL)") from exc
            except ValueError as exc:
                raise RuntimeError(f"MTR_TRACKER_DATABASE_URL is not a valid PostgreSQL URL: {exc}") from exc
            except PermissionError as exc:
                # asyncpg looks for libpq client certificates under HOME before it connects; a process dropped to
                # another user with root's environment fails every attempt this way, so waiting cannot help.
                raise RuntimeError(
                    f"cannot connect to PostgreSQL at {self.describe()}: {exc}. asyncpg reads client certificates from "
                    f"HOME={os.environ.get('HOME', '')}/.postgresql; give the process a readable HOME, or add ?sslmode=disable to "
                    "MTR_TRACKER_DATABASE_URL when the server speaks no TLS"
                ) from exc
            except _RETRY_ERRORS as exc:
                if time.monotonic() >= deadline:
                    raise RuntimeError(
                        f"PostgreSQL at {self.describe()} did not accept connections within {self.connect_timeout:.0f} s: {exc} "
                        "(MTR_TRACKER_DATABASE_URL, MTR_TRACKER_DB_CONNECT_TIMEOUT)"
                    ) from exc
                if attempt == 1 or attempt % 5 == 0:
                    log.warning("waiting for PostgreSQL at %s (attempt %d): %s", self.describe(), attempt, exc)
                await asyncio.sleep(delay)
                delay = min(5.0, delay * 2)
        async with self._connection() as conn:
            # No parameters: the simple-query protocol runs every statement of the schema in one round trip.
            await conn.execute(SCHEMA)
            await conn.execute(
                translate("INSERT INTO meta(key, value) VALUES ('schema_version', ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value"),
                str(SCHEMA_VERSION),
            )
        log.info("database ready at %s", self.describe())

    async def close(self) -> None:
        if self._pool is None:
            return
        pool = self._pool
        try:
            await asyncio.wait_for(pool.close(), 10)
        except asyncio.TimeoutError:
            log.warning("database connections did not close in time; terminating them")
            pool.terminate()
        finally:
            self._pool = None

    @asynccontextmanager
    async def transaction(self) -> AsyncIterator[Transaction]:
        """Run several statements atomically on one connection: all committed on success, none on error.

        Use only the `tx.*` methods inside the block; `db.*` runs on another pooled connection, which cannot see
        the uncommitted rows.
        """
        async with self._connection() as conn:
            async with conn.transaction():
                yield Transaction(conn)

    # -- settings --------------------------------------------------------

    async def get_settings(self) -> dict[str, Any]:
        rows = await self.fetchall("SELECT key, value FROM settings")
        result = dict(DEFAULT_SETTINGS)
        for row in rows:
            try:
                result[row["key"]] = json.loads(row["value"])
            except json.JSONDecodeError:
                result[row["key"]] = row["value"]
        return result

    async def set_settings(self, values: dict[str, Any]) -> dict[str, Any]:
        await self.executemany(
            "INSERT INTO settings(key, value) VALUES(?, ?) "
            "ON CONFLICT(key) DO UPDATE SET value = excluded.value",
            [(k, json.dumps(v)) for k, v in values.items()],
        )
        return await self.get_settings()

    # -- maintenance -----------------------------------------------------

    async def db_size_bytes(self) -> int:
        """Size of the whole database on disk (tables, indexes and the server's own catalogs)."""
        return int(await self.fetchval("SELECT pg_database_size(current_database())"))

    async def is_fresh(self) -> bool:
        """True while no target, run or event has ever been stored (the state the automatic import requires)."""
        return not await self.fetchval("SELECT EXISTS (SELECT 1 FROM targets) OR EXISTS (SELECT 1 FROM runs) OR EXISTS (SELECT 1 FROM events)")

    async def purge_older_than(self, days: int, batch: int = 5000) -> int:
        """Delete runs (hops follow by cascade) and events older than `days`.

        Runs go in batches, each its own transaction, with a yield to the event loop between them: one huge DELETE
        would hold row locks and bloat the tables for minutes when the retention window shrinks.
        """
        cutoff = time.time() - days * 86400
        removed = 0
        while True:
            n = await self.execute("DELETE FROM runs WHERE id IN (SELECT id FROM runs WHERE started_at < ? LIMIT ?)", (cutoff, batch))
            removed += n
            if n < batch:
                break
            await asyncio.sleep(0.05)
        await self.execute("DELETE FROM events WHERE created_at < ?", (cutoff,))
        return removed


def rows_to_dicts(rows: Iterable[Row]) -> list[dict[str, Any]]:
    return [dict(r) for r in rows]
